networks:
    default:
        name: milvus
        driver: bridge

services:
    jupyter-pytorch:
        image: quay.io/jupyter/pytorch-notebook:cuda12-python-3.11.8
        container_name: milvus-jupyter-pytorch
        user: root
        volumes:
            - "d:/users/cesar/dev/phd/price-catalog:/work"
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=compute,utility
            - JUPYTER_TOKEN=j # Set your own simple token here
        ports:
            - "8888:8888" # Maps port 8888 on the host to port 8888 in the container
            - "8050:8050" # Dash
        networks:
            - default
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [ gpu ]
        entrypoint: >
            /bin/bash -c " if [ -f /work/requirements.txt ]; then pip install -r /work/requirements.txt; fi && exec jupyter-lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --debug --notebook-dir=/work --ServerApp.iopub_data_rate_limit=10000000
                          "
    etcd:
        container_name: milvus-etcd
        image: quay.io/coreos/etcd:v3.5.5
        environment:
            - ETCD_AUTO_COMPACTION_MODE=revision
            - ETCD_AUTO_COMPACTION_RETENTION=1000
            - ETCD_QUOTA_BACKEND_BYTES=4294967296
            - ETCD_SNAPSHOT_COUNT=50000
        volumes:
            - "d:/users/cesar/dev/phd/price-catalog/etcd:/etcd"
        command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
        healthcheck:
            test: [ "CMD", "etcdctl", "endpoint", "health" ]
            interval: 30s
            timeout: 20s
            retries: 3

    minio:
        container_name: milvus-minio
        image: minio/minio:RELEASE.2023-03-20T20-16-18Z
        environment:
            MINIO_ACCESS_KEY: minioadmin
            MINIO_SECRET_KEY: minioadmin
        ports:
            - "9001:9001"
            - "9000:9000"
        volumes:
            - "d:/users/cesar/dev/phd/price-catalog/minio:/minio_data"
        command: minio server /minio_data --console-address ":9001"
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
            interval: 30s
            timeout: 20s
            retries: 3

    milvus-standalone:
        container_name: milvus-standalone
        image: milvusdb/milvus:v2.4.1-gpu
        command: [ "milvus", "run", "standalone" ]
        security_opt:
            - seccomp:unconfined
        environment:
            ETCD_ENDPOINTS: etcd:2379
            MINIO_ADDRESS: minio:9000
        volumes:
            - "d:/users/cesar/dev/phd/price-catalog/milvus:/var/lib/milvus"
        ports:
            - "19530:19530"
            - "9091:9091"
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [ "gpu" ]
                          device_ids: [ "0" ]
        depends_on:
            - "etcd"
            - "minio"

    attu:
        image: zilliz/attu:v2.4.0
        ports:
            - "8001:3000"
        environment:
            - MILVUS_URL=http://milvus-standalone:19530
        networks:
            - default
        depends_on:
            - milvus-standalone

    ollama:
        container_name: ollama
        image: ollama/ollama:0.3.12-rc4-rocm
        pull_policy: always
        tty: true
        restart: always
        environment:
            - OLLAMA_MAX_LOADED_MODELS=2
            - OLLAMA_NUM_PARALLEL=2
            - OLLAMA_KEEP_ALIVE=24h
            - OLLAMA_HOST=0.0.0.0
            - OLLAMA_DEBUG=1
            - NVIDIA_VISIBLE_DEVICES=all
        volumes:
            - "d:/users/cesar/dev/phd/price-catalog/ollama:/root/.ollama"
        ports:
            - "11434:11434"
        networks:
            - default
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [ "gpu" ]
