networks:
    default:
        name: bc3cat-retrieval
        driver: bridge

services:
    jupyter-pytorch:
        image: quay.io/jupyter/pytorch-notebook:cuda12-python-3.11.8
        container_name: jupyter-pytorch
        user: root
        volumes:
            - ".:/work"
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=compute,utility
            - JUPYTER_TOKEN=j # Set your own simple token here
        ports:
            - "8888:8888" # Maps port 8888 on the host to port 8888 in the container
            - "8050:8050" # Dash
        networks:
            - default
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [ gpu ]
        entrypoint: >
            /bin/bash -c " if [ -f /work/requirements.txt ]; then pip install -r /work/requirements.txt; fi && exec jupyter-lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --debug --notebook-dir=/work --ServerApp.iopub_data_rate_limit=10000000
                          "
    bge-m3:
        build:
            context: . # folder where Dockerfile.bge-m3 is located
            dockerfile: Dockerfile.bge-m3
        image: bge-m3:cuda
        container_name: bge-m3
        restart: unless-stopped
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [ "gpu" ]
        environment:
            - HF_HOME=/hf-cache
            - TRANSFORMERS_CACHE=/hf-cache/transformers
            - HF_DATASETS_CACHE=/hf-cache/datasets
            - XDG_CACHE_HOME=/hf-cache
            - HF_HUB_ENABLE_HF_TRANSFER=1
            - BGE_MODEL=BAAI/bge-m3
            - BGE_USE_FP16=true
        volumes:
            - ./work:/work
            - ./hf-cache:/hf-cache
        ports:
            - "8800:8000"
        networks:
            - default

    ollama:
        image: ollama/ollama:0.17.7
        container_name: ollama
        ports:
            - "11434:11434"
        volumes:
            - ollama-models:/root/.ollama
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [ gpu ]
        networks:
            - default
        restart: unless-stopped

volumes:
    ollama-models:
