"""S3's exit criteria, as tests rather than as a claim in the report (work item 11).

A sprint report asserts that its exit criteria were met. This file is what makes that checkable
without rerunning the sprint: the criteria that are properties of the tree — runs present and clean,
ten arms indexed, tables generated and stamped, the population each figure is computed on — are
asserted here, so a later change that quietly breaks one fails a test instead of being discovered by
the auditor.

The criteria verified elsewhere are not duplicated: the digests in `test_intake_20260927.py`, the
E3 delivery in `test_intake_e3.py`, the exclusion in `test_duplicate_exclusion.py`, the overlap
definition in `test_overlap.py`, the batching in `test_retriever_batching.py` and the worktree guard
in `test_worktree_guard.py`.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
RUNS = REPO / "runs" / "OE"
INDEX = REPO / "index" / "OE"
RESULTS = REPO / "docs" / "synthetic-oe" / "results" / "S3"

#: D-012's ten arms.
TEN = [
    "bm25_unigram_params__k1-0.60__b-0.35__OE",
    "bm25_unigram__k1-0.60__b-0.35__OE",
    "tfidf_unigram_phrases_replace__OE",
    "bge_m3_colbert__OE",
    "bge_m3_dense__OE",
    "bge_m3_sparse__OE",
    "dense_e5__OE",
    "dense_es_hiiamsid__OE",
    "dense_gte__OE",
    "dense_gte_instrQ__OE",
]

pytestmark = pytest.mark.skipif(
    not RUNS.is_dir(), reason="runs/ is git-ignored and absent in this checkout"
)


# --- criterion 3: every arm is indexed over the full corpus, cleanly ---------------------


@pytest.mark.parametrize("method", TEN)
def test_every_arm_is_indexed_over_the_full_corpus(method):
    meta = json.loads((INDEX / method / "meta.json").read_text(encoding="utf-8"))
    assert meta["num_docs"] == 70_242, "the index must cover the whole corpus (D-023)"
    assert meta["code_dirty"] is False, "an index from a dirty tree cannot be cited"


# --- criterion 4: ten identity runs and ten resumen runs, all clean ----------------------


@pytest.mark.parametrize("queryset", ["texto", "resumen"])
@pytest.mark.parametrize("method", TEN)
def test_e0_run_exists_and_is_stamped(queryset, method):
    meta = json.loads((RUNS / queryset / method / "run_meta.json").read_text(encoding="utf-8"))
    for field in ("run_id", "config_sha256", "code_commit", "query_set_sha256"):
        assert meta.get(field), f"{queryset}/{method}: {field} missing"
    assert meta["code_dirty"] is False
    assert meta["split"] == "dev", "S3 runs on dev only (operating rule 2)"
    assert meta["queries"] == 35_422


# --- criterion 7: the sweep is complete ---------------------------------------------------


def test_the_sweep_covers_every_grid_cell():
    missing = []
    for variant in ("bm25_unigram", "bm25_unigram_params"):
        for k1 in (0.60, 0.80, 1.00, 1.20, 1.40):
            for b in (0.20, 0.35, 0.50, 0.65, 0.80):
                cfg = f"{variant}__k1-{k1:.2f}__b-{b:.2f}__OE"
                for queryset in ("texto", "single_texto", "stacked_texto"):
                    if not (RUNS / queryset / cfg / "metrics_dual.json").is_file():
                        missing.append(f"{queryset}/{cfg}")
    assert not missing, f"{len(missing)} of 150 sweep cells missing, e.g. {missing[:3]}"


def test_no_sweep_run_touched_test():
    """The sweep is tuning, and tuning never sees test (operating rule 2)."""
    for path in RUNS.glob("*/bm25_unigram*__k1-*/run_meta.json"):
        assert json.loads(path.read_text(encoding="utf-8"))["split"] == "dev", path


# --- criteria 5-7: the tables exist, and say what population they are on -----------------

TABLES = [
    "e0/ceiling.md",
    "e0/replication.md",
    "e0/transferability.md",
    "e0/run_provenance.md",
    "overlap/overlap.md",
    "s2_rescored/exclusion.md",
    "s2_rescored/identity.md",
    "s2_rescored/l1_deltas.md",
    "s2_rescored/stacked.md",
    "s2_rescored/stacked_by_dose.md",
    "s2_rescored/run_provenance.md",
]


@pytest.mark.parametrize("name", TABLES)
def test_table_exists_and_names_its_generator(name):
    """Reports are generated, not typed: each table must say what produced it."""
    text = (RESULTS / name).read_text(encoding="utf-8")
    assert "Generated by `src/utils/build_" in text


@pytest.mark.parametrize("name", ["e0/ceiling.md", "e0/replication.md", "s2_rescored/identity.md"])
def test_item_level_tables_print_a_scored_n(name):
    """After the re-score every item-level Acc@1 has two values, and quoting one without its n is
    how the README's results table went wrong (D-033 note)."""
    text = (RESULTS / name).read_text(encoding="utf-8")
    assert "n scored" in text or "scored" in text


def test_the_ceiling_table_marks_the_oracle_arms():
    """D-010: an oracle arm is never quoted alone."""
    text = (RESULTS / "e0" / "ceiling.md").read_text(encoding="utf-8")
    assert text.count("**oracle**") >= 2
    assert "bm25_unigram_params" in text and "tfidf_phrases_replace" in text


def test_the_replication_table_refuses_a_paired_reading():
    """OEB test → OE dev changes chapter, corpus, query set and split; no delta is computable."""
    text = (RESULTS / "e0" / "replication.md").read_text(encoding="utf-8")
    assert "reference, not a paired contrast" in text


def test_the_replication_table_reports_hiiamsid():
    """The row the previous submission never printed (root CLAUDE.md)."""
    text = (RESULTS / "e0" / "replication.md").read_text(encoding="utf-8")
    assert "dense_es_hiiamsid" in text


def test_every_generated_table_carries_provenance_stamps():
    """Operating rule 1, applied to the tables rather than to the runs."""
    for name in TABLES:
        text = (RESULTS / name).read_text(encoding="utf-8")
        if name.endswith("run_provenance.md"):
            assert "code commit" in text
            continue
        assert re.search(r"config SHA-256|SHA-256", text), name


# --- the split is not a suggestion --------------------------------------------------------


def test_no_run_in_this_sprint_read_the_test_split():
    """The frozen test evaluation happens once, in S12. A single dev/test slip here would spend it."""
    offenders = [
        str(p.parent.relative_to(RUNS))
        for p in RUNS.rglob("run_meta.json")
        if json.loads(p.read_text(encoding="utf-8")).get("split") != "dev"
    ]
    assert not offenders, f"runs on a non-dev split: {offenders[:5]}"
