"""Build docs/synthetic-oe/MANIFEST.md — S0 work item 1.

Records, for every data file the branch depends on, a full SHA-256, byte size and
record count, and re-asserts the claims INTAKE.md makes about the corpus and query
sets. Generated, never hand-edited: run it again and it overwrites.

    python src/utils/build_manifest.py
"""

from __future__ import annotations

import hashlib
import json
import subprocess
from datetime import date
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DATA = REPO / "data" / "processed"
OUT = REPO / "docs" / "synthetic-oe" / "MANIFEST.md"

OE_CORPUS = ["OE_texto.json", "OE_resumen.json"]
OE_QUERIES = ["OE_single_texto.json", "OE_stacked_texto.json"]
OE_OTHER = ["OE_concept_schema.json"]
OEB = [
    "OEB_texto.json",
    "OEB_resumen.json",
    "OEB_long_norm.parquet",
    "OEB_short_norm.parquet",
    "OEB_long_feats.parquet",
    "OEB_short_feats.parquet",
    "OEB_features_meta.json",
]

# SHA-256 prefixes recorded at copy time, INTAKE.md §2.
INTAKE_PREFIXES = {
    "OE_single_texto.json": "b6a43961295cc2ca",
    "OE_stacked_texto.json": "1bde21157ef97421",
    "OE_concept_schema.json": "2d3273ddb3e443a1",
    "OE_texto.json": "02a2c270d7ffe147",
    "OE_resumen.json": "0cd380e9e44ad8c5",
}

# Counts INTAKE.md claims, asserted here against what the files actually hold.
INTAKE_COUNTS = {
    "corpus_records": 70242,
    "concepts": 83,
    "single_queries": 4439,
    "stacked_queries": 4998,
}


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for block in iter(lambda: fh.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


def record_count(path: Path) -> int | str:
    if path.suffix == ".parquet":
        import pyarrow.parquet as pq

        return pq.ParquetFile(path).metadata.num_rows
    obj = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(obj, list):
        return len(obj)
    if isinstance(obj, dict):
        return len(obj)
    return "n/a"


def main() -> None:
    commit = subprocess.check_output(
        ["git", "-C", str(REPO), "rev-parse", "--short", "HEAD"], text=True
    ).strip()

    rows: list[tuple[str, int, int | str, str, str]] = []
    for name in OE_CORPUS + OE_QUERIES + OE_OTHER + OEB:
        p = DATA / name
        digest = sha256(p)
        expected = INTAKE_PREFIXES.get(name)
        if expected is None:
            check = "— (no digest on record)"
        elif digest.startswith(expected):
            check = f"matches `{expected}`"
        else:
            raise SystemExit(
                f"DIGEST MISMATCH for {name}: INTAKE.md §2 records {expected}, "
                f"file is {digest[:16]}. Sprint stops here."
            )
        rows.append((name, p.stat().st_size, record_count(p), digest, check))

    # --- observed corpus and query facts ---
    texto = json.loads((DATA / "OE_texto.json").read_text(encoding="utf-8"))
    resumen = json.loads((DATA / "OE_resumen.json").read_text(encoding="utf-8"))
    single = json.loads((DATA / "OE_single_texto.json").read_text(encoding="utf-8"))
    stacked = json.loads((DATA / "OE_stacked_texto.json").read_text(encoding="utf-8"))
    schema = json.loads((DATA / "OE_concept_schema.json").read_text(encoding="utf-8"))

    corpus_keys = {r["item_key"] for r in texto}
    parents = {r["parent_key"] for r in texto}
    parent_of = {r["item_key"]: r["parent_key"] for r in texto}
    template_rows = [k for k in corpus_keys if k.endswith("$") or "#" in k]

    def gold_check(qs: list[dict]) -> tuple[int, int, int]:
        missing = sum(1 for q in qs if q["gold_item_key"] not in corpus_keys)
        mismatched = sum(
            1
            for q in qs
            if q["gold_item_key"] in corpus_keys
            and parent_of[q["gold_item_key"]] != q["parent_key"]
        )
        return len({q["gold_item_key"] for q in qs}), missing, mismatched

    s_leaves, s_missing, s_mismatch = gold_check(single)
    k_leaves, k_missing, k_mismatch = gold_check(stacked)

    observed = {
        "corpus_records": len(texto),
        "concepts": len(parents),
        "single_queries": len(single),
        "stacked_queries": len(stacked),
    }

    # --- render ---
    L: list[str] = []
    L.append("# MANIFEST — `research/synthetic-oe`")
    L.append("")
    L.append(
        "Derived. Generated by `src/utils/build_manifest.py`; never hand-edited. "
        "Re-run it to refresh."
    )
    L.append("")
    L.append(f"**Generated:** {date.today().isoformat()} · **Code commit:** `{commit}`")
    L.append("")
    L.append("---")
    L.append("")
    L.append("## Files")
    L.append("")
    L.append("| File | Bytes | Records | SHA-256 | vs `INTAKE.md §2` |")
    L.append("|---|---:|---:|---|---|")
    for name, size, n, digest, check in rows:
        L.append(f"| `{name}` | {size:,} | {n:,} | `{digest}` | {check} |")
    L.append("")
    L.append(
        "The seven `OEB_*` files carry no digest anywhere before this manifest: they were "
        "copied from `../bc3cat-dataset/data/processed/` on 2026-09-15 while repopulating "
        "`data/` after the incident (D-019). Their digests are recorded here for the first "
        "time, so they are checkable from now on but not verifiable backwards."
    )
    L.append("")
    L.append("## Claims asserted")
    L.append("")
    L.append("Every count `INTAKE.md` states, re-counted from the files themselves.")
    L.append("")
    L.append("| Claim | `INTAKE.md` | Observed | |")
    L.append("|---|---:|---:|---|")
    for key, claimed in INTAKE_COUNTS.items():
        got = observed[key]
        L.append(
            f"| {key.replace('_', ' ')} | {claimed:,} | {got:,} | "
            f"{'agrees' if got == claimed else '**DIFFERS**'} |"
        )
    L.append("")
    L.append("## Integrity checks")
    L.append("")
    L.append("| Check | Result |")
    L.append("|---|---|")
    L.append(
        f"| `OE_texto.json` and `OE_resumen.json` hold the same leaves, in the same order | "
        f"{'yes' if [r['item_key'] for r in texto] == [r['item_key'] for r in resumen] else '**NO**'} |"
    )
    L.append(
        f"| `item_key` unique across the corpus | "
        f"{'yes' if len(corpus_keys) == len(texto) else '**NO**'} |"
    )
    L.append(
        f"| Template rows (`$` / `#`) present | "
        f"{'**' + str(len(template_rows)) + '**' if template_rows else 'none'} |"
    )
    L.append(f"| Concepts in `OE_concept_schema.json` | {len(schema):,} |")
    L.append(
        f"| Single queries: gold leaves / gold absent from corpus / parent mismatch | "
        f"{s_leaves:,} / {s_missing} / {s_mismatch} |"
    )
    L.append(
        f"| Stacked queries: gold leaves / gold absent from corpus / parent mismatch | "
        f"{k_leaves:,} / {k_missing} / {k_mismatch} |"
    )
    L.append("")

    # --- OEB: reconcile the JSON record count against the parquet row count ---
    import pandas as pd

    oeb = json.loads((DATA / "OEB_texto.json").read_text(encoding="utf-8"))
    oeb_keys = {r["item_key"] for r in oeb}
    oeb_templates = sorted(k for k in oeb_keys if k.endswith("$") or "#" in k)
    norm_keys = set(pd.read_parquet(DATA / "OEB_long_norm.parquet")["item_key"].astype(str))
    only_json = sorted(oeb_keys - norm_keys)
    only_parquet = sorted(norm_keys - oeb_keys)

    L.append("## OEB: JSON against parquet")
    L.append("")
    L.append(
        f"`OEB_texto.json` holds {len(oeb):,} records and the four parquets "
        f"{len(norm_keys):,} rows. The difference is accounted for, not lost: "
        f"{len(only_json)} key(s) present in the JSON and absent from the parquets — "
        f"{', '.join('`' + k + '`' for k in only_json) if only_json else 'none'} — and "
        f"{len(only_parquet)} the other way round. "
        + (
            "Template rows are dropped by normalisation, which is the intended behaviour; "
            f"the OEB corpus still carries {len(oeb_templates)} of them "
            f"({', '.join('`' + k + '`' for k in oeb_templates)}), whereas the OE corpus "
            "carries none."
            if oeb_templates
            else ""
        )
    )
    L.append("")

    OUT.write_text("\n".join(L) + "\n", encoding="utf-8", newline="\n")
    print(f"written: {OUT.relative_to(REPO)}")
    for key, claimed in INTAKE_COUNTS.items():
        print(f"  {key}: claimed {claimed}, observed {observed[key]}")
    print(f"  single gold missing/mismatch: {s_missing}/{s_mismatch}")
    print(f"  stacked gold missing/mismatch: {k_missing}/{k_mismatch}")
    print(f"  template rows: {len(template_rows)}")


if __name__ == "__main__":
    main()
